### ISSUE TITLE
<img> tag inside cell not working

### ISSUE THREAD

**Issue by sturze** [fooplugins/FooTable#369] opened 2015-10-27 10:28 UTC
Hi!
maybe i just don't get it, or it is not possible to put a image inside a cell

``` html
<td> <img src='../file.png' /> </td>
```

also tried font-awesome, to use symbols that way... no success...

``` html
<td> <i class="fa fa-medkit"></i></td>
```

anybody else got this issue?!

**Comment by stphn** [comment] 2015-11-04 11:14
I have experienced the same issue:

```
<tr data-expanded="true">
    <td><img src="../assets/images/icons/icon--wallet.svg" width="50"></td>
    <td>13.08.2014 18:33:24</td>
    <td>Branch Refund</td>
    <td>0,10 EUR</td>
</tr>
```

It seems that all html tags inside `<td>` are killed

**Comment by sturze** [comment] 2015-11-04 14:12
yup!... can confirm that, not just images...! same issue with links! they are just gone....see --> #355 
anybody any idea how to fix it?

**Comment by antonsarov** [comment] 2015-11-06 13:01
See #355 for a temporary workaround or even contribute your own if you have :) I hope the issue is resolved soon

**Comment by dave-buzzy** [comment] 2015-12-11 03:51
Just putting this here for anyone still waiting: identical issue as #355, has been fixed as of v3.03.

**Comment by mqueirozcorreia** [comment] 2016-02-13 20:56
Can I use the `data-type="html` and `data-value`?

**Comment by sturze** [comment] 2016-02-25 12:43
yup... works with all html tags i tested so far... :smiley:

**Comment by mqueirozcorreia** [comment] 2016-02-26 00:52
The problem for me is that when I use `data-value`, it replaces the html inside the cell.
So if I use:
`<td data-value="1"> <img src='../file.png' /> </td>`

The image is replaced by the value 1.

I want to use `data-value` to make the sort works as I expect

**Comment by mqueirozcorreia** [comment] 2016-05-17 01:12
I have created a specific issue to simulate my problem at https://github.com/fooplugins/FooTable/issues/457

**Closed as completed** 2016-05-17 09:49 UTC
