### ISSUE TITLE
Emojis where the icons should be?

### ISSUE THREAD

**Issue by kgilmur** [fooplugins/FooTable#326] opened 2015-05-15 06:36 UTC
Is anyone else getting emojis popping up where the toggle icons should be only on apple products?

**Comment by cenixdk** [comment] 2015-05-22 07:39
Yes, I am getting emojis instead of sorting arrows on ios. No problems on desktop browsers.

**Comment by kavare** [comment] 2015-08-16 03:33
Same here. Both Safari and Chrome on iOS got the same issue. I guess the problem is that 'font-family': 'footable' is not working on iOS devices but unable to define the reasons.

**Comment by steveush** [comment] 2016-08-11 14:49
Hi,

V2 is no longer supported and it sat for a very long time and so issues just built up. Seeing as V3 has been the default branch for quite a while now (over a year) and development is continuing on it I am bulk closing all old V2 issues in an attempt to cleanup the repo a bit. I will also be going through the old pull requests and possibly removing the entire V2 branch as it is stagnant and just causes confusion.

V3 was designed to fill the gap between having to roll your own for simple tables and having to implement https://datatables.net/, seeing as they have copied the way the row collapsing works from FooTable they are a very good solution to use for more complex table layouts or for full ajax support.

As for this specific issue it's due to Apple force loading there emoji font which was overriding the original V2 font icons. The easiest way to "fix" it would be to simply specify `!important` after the `font-family: footable` declaration in the CSS.

V3 makes use of FontAwesome or Glyphicons for icons so this issue should no longer exist.

Thanks

**Closed as completed by steveush** 2016-08-11 14:49 UTC
