### ISSUE TITLE
filter scrolls page

### ISSUE THREAD

**Issue by macmedia** [fooplugins/FooTable#302] opened 2014-12-13 21:59 UTC
When I click a button to apply the filter it scrolls the page up. How can I stop this action from happening. Im using .preventDefault and return false.

I would like the page to stay where it is. If I comment out the "trigger" for the filter it doesn't scroll up.

Sample
http://jsfiddle.net/macmedia/bxkeeLLo/2/

**Comment by steveush** [comment] 2016-08-11 14:24
Hi,

V2 is no longer supported and it sat for a very long time and so issues just built up. Seeing as V3 has been the default branch for quite a while now (over a year) and development is continuing on it I am bulk closing all old V2 issues in an attempt to cleanup the repo a bit. I will also be going through the old pull requests and possibly removing the entire V2 branch as it is stagnant and just causes confusion.

V3 was designed to fill the gap between having to roll your own for simple tables and having to implement https://datatables.net/, seeing as they have copied the way the row collapsing works from FooTable they are a very good solution to use for more complex table layouts or for full ajax support.

As for this specific issue this isn't a problem with FooTable or your button event, the issue is simply when you filter the rows the height of the table is changed as fewer rows are displayed. With fewer rows the scrollbar is no longer necessary so the browser by default sets the scroll position back to 0 and hides the scrollbars.

Thanks

**Closed as completed by steveush** 2016-08-11 14:24 UTC
