### ISSUE TITLE
Got error when i do ajax call

### ISSUE THREAD

**Issue by rahul8sharma** [fooplugins/FooTable#486] opened 2016-07-22 07:10 UTC
$('.table').footable({
        "columns": data.game_column,
        "rows": data.game_row
      });

when i call ajax first time it will show footable and when i call second time then it will giving error.
**FooTable: unhandled error thrown during a draw operation. TypeError: Cannot read property 'toUpperCase' of undefined**
It is giving me a error at the time of alternative ajax call.

**Comment by steveush** [comment] 2016-08-11 10:56
Hi,

Any chance you can create a fiddle or supply me with a URL to see the issue? I can't replicate this so I's not sure exactly what the issue is.

Thanks

**Comment by rh1nox** [comment] 2016-08-12 11:55
@steveush 
I'm also to see this issue.
In my project, I used boostrap-treeview. I click a child node, call ajax to show footable. And when i click the node second time, the issue happend.

**Comment by rh1nox** [comment] 2016-08-14 11:14
@rahul8sharma 
Do you have solve the problem？

**Comment by steveush** [comment] 2016-08-30 18:08
Hi,

I could not replicate this issue and I haven't been given a url where I can see it and test it so I'm closing.

Thanks

**Closed as completed by steveush** 2016-08-30 18:08 UTC
